# -*- coding: utf-8 -*-
"""ML_programming assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mlo5lUzHBGEd8qfBXbERHu7nNgSBjaYZ
"""

import torch
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

"""## Dataset"""

DATA_DIR = '/content/drive/MyDrive/ML_assignment'

f = open(f"{DATA_DIR}/train.txt")
train = [float(x) for x in f.read().split()]
f.close()

train = torch.tensor(train).view(-1, 6)
X_train = train[:, :5]
Y_train = train[:, 5].long()

print(X_train.shape, X_train.dtype)
print(Y_train.shape, Y_train.dtype)

DATA_DIR = '/content/drive/MyDrive/ML_assignment'

f = open(f"{DATA_DIR}/validation.txt")
validation = [float(x) for x in f.read().split()]
f.close()

validation = torch.tensor(validation).view(-1, 6)
X_val = validation[:, :5]
Y_val = validation[:, 5].long()
print(X_val.shape, X_val.dtype)
print(Y_val.shape, Y_val.dtype)

DATA_DIR = '/content/drive/MyDrive/ML_assignment'

f = open(f"{DATA_DIR}/test.txt")
test = [float(x) for x in f.read().split()]
f.close()

test = torch.tensor(test).view(-1, 6)
X_test = test[:, :5]
Y_test = test[:, 5].long()

print(X_test.shape, X_test.dtype)
print(Y_test.shape, Y_test.dtype)

mu = X_train.mean(0)
sigma = X_train.std(0)

X_train = (X_train - mu) / sigma
X_val = (X_val - mu) / sigma
X_test = (X_test - mu) / sigma

"""## Logistic regression"""

def logreg_inference(w, b, X):
    logits = X @ w + b
    p = torch.sigmoid(logits)
    return p

LR = 0.001
STEPS = 10000

w = torch.zeros(5, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = torch.optim.SGD([w, b], lr=LR, momentum=0.9)

losses = []
steps = []

def loss_d(p, Y): # Cross entropy loss function
  l= -Y * torch.log(p) - (1 - Y) * torch.log(1 - p)
  return l.mean()

for step in range(STEPS):
    optimizer.zero_grad()
    p = logreg_inference(w, b, X_train)
    p = p.clamp(0.001, 0.999)
    loss = loss_d(p, Y_train)
    loss.backward()
    optimizer.step()

    if step % 1000 == 0:
        print(step, loss.item())
    losses.append(loss.item())
    steps.append(step)

plt.figure()
plt.plot(steps, losses)
plt.xlabel("Number of steps")
plt.ylabel("Cross entropy")
plt.title("Training Loss over Steps")
plt.savefig('loss_plot.jpg', format='jpg', bbox_inches='tight')
plt.show()

p = logreg_inference(w, b, X_train)
predictions = (p > 0.5).long()
accuracy = (predictions == Y_train).float().mean()
print("Training accuracy = ", accuracy.item())

predictions = (logreg_inference(w, b, X_test) > 0.5).long()
test_accuracy = (predictions == Y_test).float().mean()
print("Test accuracy = ", test_accuracy.item())

features = ['temperature', 'humidity', 'light', 'co2', 'humidity_ratio']
max_len = max(len(f) for f in features + ['bias'])

# Header
print(f"{'Feature':<{max_len}} | Weight")
print("-" * (max_len + 10))

# Rows
for feat in range(5):
    print(f"{features[feat]:<{max_len}} | {w[feat].item():.4f}")

# Bias
print("-" * (max_len + 10))
print(f"{'bias':<{max_len}} | {b.item():.4f}")

"""## Multilayer Perceptron"""

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(DEVICE)

net_1 = torch.nn.Sequential(
    torch.nn.Linear(5, 2),
    torch.nn.ReLU(),
    torch.nn.Linear(2, 2)
)
net_1.to(DEVICE)

ps = sum(p.numel() for p in net_1.parameters())
print(f"Number of parameters: {ps}")

net_2 = torch.nn.Sequential(
    torch.nn.Linear(5, 4),
    torch.nn.ReLU(),
    torch.nn.Linear(4, 2)
)
net_2.to(DEVICE)

ps = sum(p.numel() for p in net_2.parameters())
print(f"Number of parameters: {ps}")

net_3 = torch.nn.Sequential(
    torch.nn.Linear(5, 2),
    torch.nn.ReLU(),
    torch.nn.Linear(2, 2),
    torch.nn.ReLU(),
    torch.nn.Linear(2, 2)
)
net_3.to(DEVICE)

ps = sum(p.numel() for p in net_3.parameters())
print(f"Number of parameters: {ps}")

nets = [net_1, net_2, net_3]

BATCH_SIZE = 64

train_dataset = torch.utils.data.TensorDataset(X_train, Y_train)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

val_dataset = torch.utils.data.TensorDataset(X_val, Y_val)
val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

test_dataset = torch.utils.data.TensorDataset(X_test, Y_test)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

def train(net, LR, EPOCHS, MOMENTUM):
    loss_fun = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(net.parameters(), lr=LR, momentum=MOMENTUM)
    steps = 0

    epochs_list = []
    train_accs = []
    test_accs = []

    for epoch in range(EPOCHS):
        net.train()
        for features, labels in train_loader:
            features = features.to(DEVICE)
            labels = labels.to(DEVICE)
            optimizer.zero_grad()
            logits = net(features)
            loss = loss_fun(logits, labels)
            loss.backward()
            optimizer.step()
            steps += 1
            if steps % 1000 == 0:
                predictions = torch.argmax(logits, dim=1)
                accuracy = (predictions == labels).float().mean()
                print(f"Epoch {epoch} step {steps} loss {loss.item():.4f} acc. {accuracy * 100:.1f}%")

        net.eval()
        with torch.no_grad():
            train_logits = net(X_train.to(DEVICE))
            train_pred = torch.argmax(train_logits, dim=1)
            train_accuracy = (train_pred == Y_train.to(DEVICE)).float().mean().item() * 100

            test_logits = net(X_test.to(DEVICE))
            test_pred = torch.argmax(test_logits, dim=1)
            test_accuracy = (test_pred == Y_test.to(DEVICE)).float().mean().item() * 100

        epochs_list.append(epoch)
        train_accs.append(train_accuracy)
        test_accs.append(test_accuracy)

    return net, epochs_list, train_accs, test_accs

def train_acc(NET):
    ok = 0
    tot = 0

    for features, labels in train_loader:
        features = features.to(DEVICE)
        labels = labels.to(DEVICE)
        with torch.no_grad():
            logits = NET(features)
        predictions = torch.argmax(logits, dim=1)
        ok += (predictions == labels).long().sum()
        tot += len(labels)

    accuracy = (ok / tot).item() * 100
    return accuracy

def val_acc(NET):
    ok = 0
    tot = 0
    for features, labels in val_loader:
        features = features.to(DEVICE)
        labels = labels.to(DEVICE)
        with torch.no_grad():
            logits = NET(features)
        predictions = torch.argmax(logits, dim=1)
        ok += (predictions == labels).long().sum()
        tot += len(labels)
    accuracy = (ok / tot).item() * 100
    return accuracy

def test_acc(NET):
    ok = 0
    tot = 0

    for features, labels in test_loader:
        features = features.to(DEVICE)
        labels = labels.to(DEVICE)
        with torch.no_grad():
            logits = NET(features)
        predictions = torch.argmax(logits, dim=1)
        ok += (predictions == labels).long().sum()
        tot += len(labels)

    accuracy = (ok / tot).item() * 100
    return accuracy

LR = 0.01
MOMENTUM = 0.9
EPOCHS = 100

trained_nets = []
histories = {}

for i, net in enumerate(nets):
    print(f"\n--- Training net {i+1} ---")
    net, epochs_list, train_accs, test_accs = train(net, LR, EPOCHS, MOMENTUM)
    trained_nets.append(net)
    histories[i] = {
        "epochs": epochs_list,
        "train_acc": train_accs,
        "test_acc": test_accs
    }

nets = trained_nets

h = histories[0]

plt.figure()
plt.plot(h["epochs"], h["train_acc"], label="Training", color="blue")
plt.plot(h["epochs"], h["test_acc"], label="Test", color="red")
plt.xlabel("Epochs")
plt.ylabel("Accuracy (%)")
plt.title("Net 1: Training vs Test Accuracy over Epochs")
plt.legend()
#plt.grid(True)
plt.savefig("MLP accuracy.jpg", dpi=300, bbox_inches="tight")
plt.show()

results = []

for i, net in enumerate(nets):
    net.eval()
    train_accuracy = train_acc(net)
    validation_accuracy = val_acc(net)
    test_accuracy = test_acc(net)

    results.append({
        "net": i+1,
        "train_acc": train_accuracy,
        "val_acc": validation_accuracy,
        "test_acc": test_accuracy
    })

    print(f"Net {i+1}: train={train_accuracy:.2f}%  val={validation_accuracy:.2f}%  test={test_accuracy:.2f}%")

print("\n--- Summary ---")
print(f"{'Net':<6}{'Train':>10}{'Val':>10}{'Test':>10}")
for r in results:
    print(f"{r['net']:<6}{r['train_acc']:>9.2f}%{r['val_acc']:>9.2f}%{r['test_acc']:>9.2f}%")

"""## Error analysis"""

class_names = ["not occupied", "occupied"]

p_test = logreg_inference(w, b, X_test)
predictions = (p_test > 0.5).long()

codes = Y_test * 2 + predictions
hist = torch.bincount(codes, minlength=2 ** 2)
cm = hist.view(2, 2)

cm_norm = cm / cm.sum(1).unsqueeze(1)  # Normalization

plt.figure(dpi=100)
plt.imshow(cm_norm, cmap="Blues")
plt.xticks(range(2), class_names)
plt.yticks(range(2), class_names)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix - Logistic Regression")
plt.colorbar()
for i in range(2):
    for j in range(2):
        plt.text(j, i, f"{cm_norm[i, j].item():.2f}", ha="center", va="center",
                  color="white" if cm_norm[i, j] > 0.5 else "black")
plt.savefig("confusion_matrix_logreg.jpg", dpi=300, bbox_inches="tight")
plt.show()

cm = torch.zeros(2, 2, dtype=int)

net_1.eval()
for features, labels in test_loader:
    features = features.to(DEVICE)
    labels = labels.to(DEVICE)
    with torch.no_grad():
        logits = net_1(features)
    predictions = torch.argmax(logits, dim=1)
    codes = labels * 2 + predictions
    hist = torch.bincount(codes.cpu(), minlength=2 ** 2)
    cm += hist.view(2, 2)

cm_norm = cm / cm.sum(1).unsqueeze(1)  # Normalization

class_names = ["not occupied", "occupied"]

plt.figure(dpi=100)
plt.imshow(cm_norm, cmap="Blues")
plt.xticks(range(2), class_names)
plt.yticks(range(2), class_names)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix - MLP")
plt.colorbar()
for i in range(2):
    for j in range(2):
        plt.text(j, i, f"{cm_norm[i, j].item():.2f}", ha="center", va="center",
                  color="white" if cm_norm[i, j] > 0.5 else "black")
plt.savefig("confusion_matrix_mlp.jpg", dpi=300, bbox_inches="tight")
plt.show()

p_test = logreg_inference(w, b, X_test)
predictions = (p_test > 0.5).long()

errors_mask = predictions != Y_test
error_indices = torch.where(errors_mask)[0]

error_confidences = (p_test[error_indices] - 0.5).abs()
sorted_order = error_confidences.argsort(descending=True)

top_indices = error_indices[sorted_order[:10]] # This lines controls the number of samples plotted

features = ['temperature', 'humidity', 'light', 'co2', 'humidity_ratio']
class_names = ["not occupied", "occupied"]

for rank, idx in enumerate(top_indices):
    idx = idx.item()
    print(f"[{rank+1}] Sample {idx}")
    print(f"    True: {class_names[Y_test[idx].item()]}  Predicted: {class_names[predictions[idx].item()]}  p = {p_test[idx].item():.4f}")
    for f_name, f_val in zip(features, X_test[idx]):
        print(f"    {f_name}: {f_val.item():.4f}")
    print()

net_1.eval()
with torch.no_grad():
    logits_test = net_1(X_test.to(DEVICE))
    probs_test = torch.softmax(logits_test, dim=1)
    predictions_mlp = torch.argmax(logits_test, dim=1)

Y_test_device = Y_test.to(DEVICE)
errors_mask_mlp = predictions_mlp != Y_test_device
error_indices_mlp = torch.where(errors_mask_mlp)[0]

error_confidences_mlp = probs_test[error_indices_mlp, predictions_mlp[error_indices_mlp]]
sorted_order_mlp = error_confidences_mlp.argsort(descending=True)

top_indices_mlp = error_indices_mlp[sorted_order_mlp[:10]] # This lines controls the number of samples plotted

for rank, idx in enumerate(top_indices_mlp):
    idx = idx.item()
    print(f"[{rank+1}] Sample {idx}")
    print(f"    True: {class_names[Y_test[idx].item()]}")
    print(f"    Predicted: {class_names[predictions_mlp[idx].item()]}")
    print(f"    p = {probs_test[idx, predictions_mlp[idx]].item():.4f}")
    for f_name, f_val in zip(features, X_test[idx]):
        print(f"    {f_name}: {f_val.item():.4f}")
    print()

"""## Special request"""

def precision_recall_at_bias(w, b_offset, X, Y):
    p = logreg_inference(w, b + b_offset, X)
    predictions = (p > 0.5).long()

    tp = ((predictions == 1) & (Y == 1)).sum().item()
    fp = ((predictions == 1) & (Y == 0)).sum().item()
    fn = ((predictions == 0) & (Y == 1)).sum().item()

    precision = tp / (tp + fp) if (tp + fp) > 0 else 1.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    return precision, recall

b_offsets = torch.linspace(-10, 10, 2000)

precisions = []
recalls = []

for offset in b_offsets:
    prec, rec = precision_recall_at_bias(w, offset.item(), X_val, Y_val)
    precisions.append(prec)
    recalls.append(rec)

plt.figure()
plt.plot(recalls, precisions)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve (Logistic Regression)")
#plt.grid(True)
plt.savefig("Precision_recall_logistic.jpg", dpi=300, bbox_inches="tight")
plt.show()

def precision_recall_at_bias_offset(NET, b_offset, X, Y):
    original_bias = NET[-1].bias.data.clone()  # salva il bias originale dell'ultimo layer

    NET[-1].bias.data[1] += b_offset  # sposta solo il bias della classe 1

    NET.eval()
    with torch.no_grad():
        logits = NET(X.to(DEVICE))
        predictions = torch.argmax(logits, dim=1)

    NET[-1].bias.data = original_bias  # ripristina il bias originale

    Y = Y.to(DEVICE)
    tp = ((predictions == 1) & (Y == 1)).sum().item()
    fp = ((predictions == 1) & (Y == 0)).sum().item()
    fn = ((predictions == 0) & (Y == 1)).sum().item()

    precision = tp / (tp + fp) if (tp + fp) > 0 else 1.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    return precision, recall

b_offsets = torch.linspace(-10, 25, 2000)

precisions = []
recalls = []

for offset in b_offsets:
    prec, rec = precision_recall_at_bias_offset(net_1, offset.item(), X_val, Y_val)
    precisions.append(prec)
    recalls.append(rec)

plt.figure()
plt.plot(recalls, precisions)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve (MLP)")
#plt.grid(True)
plt.savefig("Precision_recall_MLP.jpg", dpi=300, bbox_inches="tight")
plt.show()

def metrics_at_bias(w, b_offset, X, Y):
    p = logreg_inference(w, b + b_offset, X)
    predictions = (p > 0.5).long()

    tp = ((predictions == 1) & (Y == 1)).sum().item()
    fp = ((predictions == 1) & (Y == 0)).sum().item()
    fn = ((predictions == 0) & (Y == 1)).sum().item()
    tn = ((predictions == 0) & (Y == 0)).sum().item()

    accuracy = (tp + tn) / len(Y)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 1.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    return accuracy, tp, fp, precision, recall


b_values = list(range(-11, 9))

print(f"{'b':>4} | {'Acc.':>7} | {'# T.P.':>7} | {'# F.P.':>7} | {'Prec.':>7} | {'Rec.':>7}")
print("-" * 55)

for b_offset in b_values:
    accuracy, tp, fp, precision, recall = metrics_at_bias(w, b_offset, X_val, Y_val)
    print(f"{b_offset:>4} | {accuracy*100:>6.1f}% | {tp:>7} | {fp:>7} | {precision*100:>6.1f}% | {recall*100:>6.1f}%")

def metrics_at_bias_offset(NET, b_offset, X, Y):
    original_bias = NET[-1].bias.data.clone()
    NET[-1].bias.data[1] += b_offset

    NET.eval()
    with torch.no_grad():
        logits = NET(X.to(DEVICE))
        predictions = torch.argmax(logits, dim=1)

    NET[-1].bias.data = original_bias

    Y = Y.to(DEVICE)
    tp = ((predictions == 1) & (Y == 1)).sum().item()
    fp = ((predictions == 1) & (Y == 0)).sum().item()
    fn = ((predictions == 0) & (Y == 1)).sum().item()
    tn = ((predictions == 0) & (Y == 0)).sum().item()

    accuracy = (tp + tn) / len(Y)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 1.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    return accuracy, tp, fp, precision, recall


b_values = list(range(-11, 11))

print(f"{'b':>4} | {'Acc.':>7} | {'# T.P.':>7} | {'# F.P.':>7} | {'Prec.':>7} | {'Rec.':>7}")
print("-" * 55)

for b_offset in b_values:
    accuracy, tp, fp, precision, recall = metrics_at_bias_offset(net_1, b_offset, X_val, Y_val)
    print(f"{b_offset:>4} | {accuracy*100:>6.1f}% | {tp:>7} | {fp:>7} | {precision*100:>6.1f}% | {recall*100:>6.1f}%")